version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data/elasticsearch-data:/data:rw
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  www:
    build: ./DockerFiles/www
    ports:
      - 8081:8081
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - ./target:/www
  redis:
    build: ./DockerFiles/redis
    ports:
    - 6363:6379
    volumes:
      - ./data/data_redis:/data:rw
networks:
  default:
    name: hoor
    driver: bridge
